/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DateStr = IDL.Text;
export const CallHistory = IDL.Record({
  'remark' : IDL.Text,
  'status' : IDL.Text,
  'projectName' : IDL.Text,
  'date' : DateStr,
  'name' : IDL.Text,
  'telecaller' : IDL.Text,
  'mobile' : IDL.Text,
});
export const LeadId = IDL.Nat;
export const StatusDates = IDL.Vec(IDL.Tuple(IDL.Text, DateStr));
export const Lead = IDL.Record({
  'id' : LeadId,
  'leadDate' : DateStr,
  'svRemark' : IDL.Text,
  'svStatus' : IDL.Text,
  'projectName' : IDL.Text,
  'lossReason' : IDL.Text,
  'source' : IDL.Text,
  'statusDates' : StatusDates,
  'srNo' : IDL.Nat,
  'mobileNo' : IDL.Text,
  'leadCloseStatus' : IDL.Text,
  'svNextFollowup' : DateStr,
  'requirement' : IDL.Text,
  'assignedSales' : IDL.Text,
  'remarks1' : IDL.Text,
  'remarks2' : IDL.Text,
  'telecaller' : IDL.Text,
  'statusDate' : DateStr,
  'latestStatus' : IDL.Text,
  'latestStatusDate' : DateStr,
  'budget' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const Project = IDL.Record({
  'brochure' : IDL.Text,
  'projectName' : IDL.Text,
});
export const InquiryId = IDL.Nat;
export const ProjectInquiry = IDL.Record({
  'id' : InquiryId,
  'svPlan' : DateStr,
  'projectName' : IDL.Text,
  'source' : IDL.Text,
  'name' : IDL.Text,
  'srNo' : IDL.Nat,
  'mobile' : IDL.Text,
});
export const SalesCallHistory = IDL.Record({
  'remark' : IDL.Text,
  'status' : IDL.Text,
  'projectName' : IDL.Text,
  'date' : DateStr,
  'name' : IDL.Text,
  'salesPerson' : IDL.Text,
  'mobile' : IDL.Text,
});
export const SoftwareInquiry = IDL.Record({
  'name' : IDL.Text,
  'mobile' : IDL.Text,
});
export const TaskId = IDL.Nat;
export const Task = IDL.Record({
  'status' : IDL.Text,
  'assignedTo' : IDL.Text,
  'createdBy' : IDL.Text,
  'role' : IDL.Text,
  'createdDate' : DateStr,
  'dueDate' : DateStr,
  'taskTitle' : IDL.Text,
  'description' : IDL.Text,
  'taskId' : TaskId,
  'leadSr' : IDL.Nat,
});
export const Telecaller = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const ColumnDef = IDL.Record({
  'key' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'colLabel' : IDL.Text,
  'visible' : IDL.Bool,
  'colType' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addCallHistory' : IDL.Func([CallHistory], [], []),
  'addLead' : IDL.Func([Lead], [Lead], []),
  'addProject' : IDL.Func([Project], [], []),
  'addProjectInquiry' : IDL.Func([ProjectInquiry], [ProjectInquiry], []),
  'addSalesCallHistory' : IDL.Func([SalesCallHistory], [], []),
  'addSoftwareInquiry' : IDL.Func([SoftwareInquiry], [], []),
  'addTask' : IDL.Func([Task], [Task], []),
  'addTelecaller' : IDL.Func([Telecaller], [], []),
  'deleteLead' : IDL.Func([LeadId], [IDL.Bool], []),
  'deleteProject' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteProjectInquiry' : IDL.Func([InquiryId], [IDL.Bool], []),
  'deleteTask' : IDL.Func([TaskId], [IDL.Bool], []),
  'deleteTelecaller' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getAllProjectInquiries' : IDL.Func([], [IDL.Vec(ProjectInquiry)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAllSoftwareInquiries' : IDL.Func(
      [],
      [IDL.Vec(SoftwareInquiry)],
      ['query'],
    ),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllTelecallers' : IDL.Func([], [IDL.Vec(Telecaller)], ['query']),
  'getBrochureLink' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getCallHistory' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(CallHistory)],
      ['query'],
    ),
  'getLeadById' : IDL.Func([LeadId], [IDL.Opt(Lead)], ['query']),
  'getLeadSchema' : IDL.Func([], [IDL.Vec(ColumnDef)], ['query']),
  'getLeadsBySalesPerson' : IDL.Func([IDL.Text], [IDL.Vec(Lead)], ['query']),
  'getLeadsByTelecaller' : IDL.Func([IDL.Text], [IDL.Vec(Lead)], ['query']),
  'getSalesCallHistory' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(SalesCallHistory)],
      ['query'],
    ),
  'getTaskById' : IDL.Func([TaskId], [IDL.Opt(Task)], ['query']),
  'getTasksByAssignee' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getUniqueProjectNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUniqueSalesPersons' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUniqueTelecallers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'removeColumnDef' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateLead' : IDL.Func([Lead], [IDL.Bool], []),
  'updateProject' : IDL.Func([IDL.Text, Project], [IDL.Bool], []),
  'updateTask' : IDL.Func([Task], [IDL.Bool], []),
  'updateTaskStatus' : IDL.Func([TaskId, IDL.Text], [IDL.Bool], []),
  'updateTelecaller' : IDL.Func([IDL.Text, Telecaller], [IDL.Bool], []),
  'upsertColumnDef' : IDL.Func([ColumnDef], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DateStr = IDL.Text;
  const CallHistory = IDL.Record({
    'remark' : IDL.Text,
    'status' : IDL.Text,
    'projectName' : IDL.Text,
    'date' : DateStr,
    'name' : IDL.Text,
    'telecaller' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const LeadId = IDL.Nat;
  const StatusDates = IDL.Vec(IDL.Tuple(IDL.Text, DateStr));
  const Lead = IDL.Record({
    'id' : LeadId,
    'leadDate' : DateStr,
    'svRemark' : IDL.Text,
    'svStatus' : IDL.Text,
    'projectName' : IDL.Text,
    'lossReason' : IDL.Text,
    'source' : IDL.Text,
    'statusDates' : StatusDates,
    'srNo' : IDL.Nat,
    'mobileNo' : IDL.Text,
    'leadCloseStatus' : IDL.Text,
    'svNextFollowup' : DateStr,
    'requirement' : IDL.Text,
    'assignedSales' : IDL.Text,
    'remarks1' : IDL.Text,
    'remarks2' : IDL.Text,
    'telecaller' : IDL.Text,
    'statusDate' : DateStr,
    'latestStatus' : IDL.Text,
    'latestStatusDate' : DateStr,
    'budget' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const Project = IDL.Record({
    'brochure' : IDL.Text,
    'projectName' : IDL.Text,
  });
  const InquiryId = IDL.Nat;
  const ProjectInquiry = IDL.Record({
    'id' : InquiryId,
    'svPlan' : DateStr,
    'projectName' : IDL.Text,
    'source' : IDL.Text,
    'name' : IDL.Text,
    'srNo' : IDL.Nat,
    'mobile' : IDL.Text,
  });
  const SalesCallHistory = IDL.Record({
    'remark' : IDL.Text,
    'status' : IDL.Text,
    'projectName' : IDL.Text,
    'date' : DateStr,
    'name' : IDL.Text,
    'salesPerson' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const SoftwareInquiry = IDL.Record({
    'name' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const TaskId = IDL.Nat;
  const Task = IDL.Record({
    'status' : IDL.Text,
    'assignedTo' : IDL.Text,
    'createdBy' : IDL.Text,
    'role' : IDL.Text,
    'createdDate' : DateStr,
    'dueDate' : DateStr,
    'taskTitle' : IDL.Text,
    'description' : IDL.Text,
    'taskId' : TaskId,
    'leadSr' : IDL.Nat,
  });
  const Telecaller = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const ColumnDef = IDL.Record({
    'key' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'colLabel' : IDL.Text,
    'visible' : IDL.Bool,
    'colType' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addCallHistory' : IDL.Func([CallHistory], [], []),
    'addLead' : IDL.Func([Lead], [Lead], []),
    'addProject' : IDL.Func([Project], [], []),
    'addProjectInquiry' : IDL.Func([ProjectInquiry], [ProjectInquiry], []),
    'addSalesCallHistory' : IDL.Func([SalesCallHistory], [], []),
    'addSoftwareInquiry' : IDL.Func([SoftwareInquiry], [], []),
    'addTask' : IDL.Func([Task], [Task], []),
    'addTelecaller' : IDL.Func([Telecaller], [], []),
    'deleteLead' : IDL.Func([LeadId], [IDL.Bool], []),
    'deleteProject' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteProjectInquiry' : IDL.Func([InquiryId], [IDL.Bool], []),
    'deleteTask' : IDL.Func([TaskId], [IDL.Bool], []),
    'deleteTelecaller' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getAllProjectInquiries' : IDL.Func(
        [],
        [IDL.Vec(ProjectInquiry)],
        ['query'],
      ),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAllSoftwareInquiries' : IDL.Func(
        [],
        [IDL.Vec(SoftwareInquiry)],
        ['query'],
      ),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllTelecallers' : IDL.Func([], [IDL.Vec(Telecaller)], ['query']),
    'getBrochureLink' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getCallHistory' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(CallHistory)],
        ['query'],
      ),
    'getLeadById' : IDL.Func([LeadId], [IDL.Opt(Lead)], ['query']),
    'getLeadSchema' : IDL.Func([], [IDL.Vec(ColumnDef)], ['query']),
    'getLeadsBySalesPerson' : IDL.Func([IDL.Text], [IDL.Vec(Lead)], ['query']),
    'getLeadsByTelecaller' : IDL.Func([IDL.Text], [IDL.Vec(Lead)], ['query']),
    'getSalesCallHistory' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(SalesCallHistory)],
        ['query'],
      ),
    'getTaskById' : IDL.Func([TaskId], [IDL.Opt(Task)], ['query']),
    'getTasksByAssignee' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'getUniqueProjectNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUniqueSalesPersons' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUniqueTelecallers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'removeColumnDef' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateLead' : IDL.Func([Lead], [IDL.Bool], []),
    'updateProject' : IDL.Func([IDL.Text, Project], [IDL.Bool], []),
    'updateTask' : IDL.Func([Task], [IDL.Bool], []),
    'updateTaskStatus' : IDL.Func([TaskId, IDL.Text], [IDL.Bool], []),
    'updateTelecaller' : IDL.Func([IDL.Text, Telecaller], [IDL.Bool], []),
    'upsertColumnDef' : IDL.Func([ColumnDef], [], []),
  });
};

export const init = ({ IDL }) => { return []; };