/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CallHistory {
  'remark' : string,
  'status' : string,
  'projectName' : string,
  'date' : DateStr,
  'name' : string,
  'telecaller' : string,
  'mobile' : string,
}
export interface ColumnDef {
  'key' : string,
  'sortOrder' : bigint,
  'colLabel' : string,
  'visible' : boolean,
  'colType' : string,
  'options' : Array<string>,
}
export type DateStr = string;
export type InquiryId = bigint;
export interface Lead {
  'id' : LeadId,
  'leadDate' : DateStr,
  'svRemark' : string,
  'svStatus' : string,
  'projectName' : string,
  'lossReason' : string,
  'source' : string,
  'statusDates' : StatusDates,
  'srNo' : bigint,
  'mobileNo' : string,
  'leadCloseStatus' : string,
  'svNextFollowup' : DateStr,
  'requirement' : string,
  'assignedSales' : string,
  'remarks1' : string,
  'remarks2' : string,
  'telecaller' : string,
  'statusDate' : DateStr,
  'latestStatus' : string,
  'latestStatusDate' : DateStr,
  'budget' : string,
  'lastName' : string,
  'firstName' : string,
}
export type LeadId = bigint;
export interface Project { 'brochure' : string, 'projectName' : string }
export interface ProjectInquiry {
  'id' : InquiryId,
  'svPlan' : DateStr,
  'projectName' : string,
  'source' : string,
  'name' : string,
  'srNo' : bigint,
  'mobile' : string,
}
export interface SalesCallHistory {
  'remark' : string,
  'status' : string,
  'projectName' : string,
  'date' : DateStr,
  'name' : string,
  'salesPerson' : string,
  'mobile' : string,
}
export interface SoftwareInquiry { 'name' : string, 'mobile' : string }
export type StatusDates = Array<[string, DateStr]>;
export interface Task {
  'status' : string,
  'assignedTo' : string,
  'createdBy' : string,
  'role' : string,
  'createdDate' : DateStr,
  'dueDate' : DateStr,
  'taskTitle' : string,
  'description' : string,
  'taskId' : TaskId,
  'leadSr' : bigint,
}
export type TaskId = bigint;
export interface Telecaller { 'name' : string, 'role' : string }
export interface _SERVICE {
  'addCallHistory' : ActorMethod<[CallHistory], undefined>,
  'addLead' : ActorMethod<[Lead], Lead>,
  'addProject' : ActorMethod<[Project], undefined>,
  'addProjectInquiry' : ActorMethod<[ProjectInquiry], ProjectInquiry>,
  'addSalesCallHistory' : ActorMethod<[SalesCallHistory], undefined>,
  'addSoftwareInquiry' : ActorMethod<[SoftwareInquiry], undefined>,
  'addTask' : ActorMethod<[Task], Task>,
  'addTelecaller' : ActorMethod<[Telecaller], undefined>,
  'deleteLead' : ActorMethod<[LeadId], boolean>,
  'deleteProject' : ActorMethod<[string], boolean>,
  'deleteProjectInquiry' : ActorMethod<[InquiryId], boolean>,
  'deleteTask' : ActorMethod<[TaskId], boolean>,
  'deleteTelecaller' : ActorMethod<[string], boolean>,
  'getAllLeads' : ActorMethod<[], Array<Lead>>,
  'getAllProjectInquiries' : ActorMethod<[], Array<ProjectInquiry>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getAllSoftwareInquiries' : ActorMethod<[], Array<SoftwareInquiry>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAllTelecallers' : ActorMethod<[], Array<Telecaller>>,
  'getBrochureLink' : ActorMethod<[string], [] | [string]>,
  'getCallHistory' : ActorMethod<[[] | [string]], Array<CallHistory>>,
  'getLeadById' : ActorMethod<[LeadId], [] | [Lead]>,
  'getLeadSchema' : ActorMethod<[], Array<ColumnDef>>,
  'getLeadsBySalesPerson' : ActorMethod<[string], Array<Lead>>,
  'getLeadsByTelecaller' : ActorMethod<[string], Array<Lead>>,
  'getSalesCallHistory' : ActorMethod<[[] | [string]], Array<SalesCallHistory>>,
  'getTaskById' : ActorMethod<[TaskId], [] | [Task]>,
  'getTasksByAssignee' : ActorMethod<[string], Array<Task>>,
  'getUniqueProjectNames' : ActorMethod<[], Array<string>>,
  'getUniqueSalesPersons' : ActorMethod<[], Array<string>>,
  'getUniqueTelecallers' : ActorMethod<[], Array<string>>,
  'removeColumnDef' : ActorMethod<[string], boolean>,
  'updateLead' : ActorMethod<[Lead], boolean>,
  'updateProject' : ActorMethod<[string, Project], boolean>,
  'updateTask' : ActorMethod<[Task], boolean>,
  'updateTaskStatus' : ActorMethod<[TaskId, string], boolean>,
  'updateTelecaller' : ActorMethod<[string, Telecaller], boolean>,
  'upsertColumnDef' : ActorMethod<[ColumnDef], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];