/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProjectInquiry {
    id: InquiryId;
    svPlan: DateStr;
    projectName: string;
    source: string;
    name: string;
    srNo: bigint;
    mobile: string;
}
export type LeadId = bigint;
export interface Task {
    status: string;
    assignedTo: string;
    createdBy: string;
    role: string;
    createdDate: DateStr;
    dueDate: DateStr;
    taskTitle: string;
    description: string;
    taskId: TaskId;
    leadSr: bigint;
}
export interface ColumnDef {
    key: string;
    sortOrder: bigint;
    colLabel: string;
    visible: boolean;
    colType: string;
    options: Array<string>;
}
export interface SalesCallHistory {
    remark: string;
    status: string;
    projectName: string;
    date: DateStr;
    name: string;
    salesPerson: string;
    mobile: string;
}
export type StatusDates = Array<[string, DateStr]>;
export interface Lead {
    id: LeadId;
    leadDate: DateStr;
    svRemark: string;
    svStatus: string;
    projectName: string;
    lossReason: string;
    source: string;
    statusDates: StatusDates;
    srNo: bigint;
    mobileNo: string;
    leadCloseStatus: string;
    svNextFollowup: DateStr;
    requirement: string;
    assignedSales: string;
    remarks1: string;
    remarks2: string;
    telecaller: string;
    statusDate: DateStr;
    latestStatus: string;
    latestStatusDate: DateStr;
    budget: string;
    lastName: string;
    firstName: string;
}
export type InquiryId = bigint;
export type TaskId = bigint;
export interface Telecaller {
    name: string;
    role: string;
}
export interface SoftwareInquiry {
    name: string;
    mobile: string;
}
export interface Project {
    brochure: string;
    projectName: string;
}
export interface CallHistory {
    remark: string;
    status: string;
    projectName: string;
    date: DateStr;
    name: string;
    telecaller: string;
    mobile: string;
}
export type DateStr = string;
export interface backendInterface {
    addCallHistory(entry: CallHistory): Promise<void>;
    addLead(lead: Lead): Promise<Lead>;
    addProject(project: Project): Promise<void>;
    addProjectInquiry(inquiry: ProjectInquiry): Promise<ProjectInquiry>;
    addSalesCallHistory(entry: SalesCallHistory): Promise<void>;
    addSoftwareInquiry(inquiry: SoftwareInquiry): Promise<void>;
    addTask(task: Task): Promise<Task>;
    addTelecaller(t: Telecaller): Promise<void>;
    deleteLead(id: LeadId): Promise<boolean>;
    deleteProject(name: string): Promise<boolean>;
    deleteProjectInquiry(id: InquiryId): Promise<boolean>;
    deleteTask(taskId: TaskId): Promise<boolean>;
    deleteTelecaller(name: string): Promise<boolean>;
    getAllLeads(): Promise<Array<Lead>>;
    getAllProjectInquiries(): Promise<Array<ProjectInquiry>>;
    getAllProjects(): Promise<Array<Project>>;
    getAllSoftwareInquiries(): Promise<Array<SoftwareInquiry>>;
    getAllTasks(): Promise<Array<Task>>;
    getAllTelecallers(): Promise<Array<Telecaller>>;
    getBrochureLink(projectName: string): Promise<string | null>;
    getCallHistory(telecaller: string | null): Promise<Array<CallHistory>>;
    getLeadById(id: LeadId): Promise<Lead | null>;
    getLeadSchema(): Promise<Array<ColumnDef>>;
    getLeadsBySalesPerson(salesPerson: string): Promise<Array<Lead>>;
    getLeadsByTelecaller(telecaller: string): Promise<Array<Lead>>;
    getSalesCallHistory(salesPerson: string | null): Promise<Array<SalesCallHistory>>;
    getTaskById(taskId: TaskId): Promise<Task | null>;
    getTasksByAssignee(assignedTo: string): Promise<Array<Task>>;
    getUniqueProjectNames(): Promise<Array<string>>;
    getUniqueSalesPersons(): Promise<Array<string>>;
    getUniqueTelecallers(): Promise<Array<string>>;
    removeColumnDef(key: string): Promise<boolean>;
    updateLead(lead: Lead): Promise<boolean>;
    updateProject(name: string, updated: Project): Promise<boolean>;
    updateTask(task: Task): Promise<boolean>;
    updateTaskStatus(taskId: TaskId, status: string): Promise<boolean>;
    updateTelecaller(name: string, updated: Telecaller): Promise<boolean>;
    upsertColumnDef(col: ColumnDef): Promise<void>;
}
import type { Lead as _Lead, Task as _Task } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCallHistory(arg0: CallHistory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCallHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCallHistory(arg0);
            return result;
        }
    }
    async addLead(arg0: Lead): Promise<Lead> {
        if (this.processError) {
            try {
                const result = await this.actor.addLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLead(arg0);
            return result;
        }
    }
    async addProject(arg0: Project): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProject(arg0);
            return result;
        }
    }
    async addProjectInquiry(arg0: ProjectInquiry): Promise<ProjectInquiry> {
        if (this.processError) {
            try {
                const result = await this.actor.addProjectInquiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProjectInquiry(arg0);
            return result;
        }
    }
    async addSalesCallHistory(arg0: SalesCallHistory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSalesCallHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSalesCallHistory(arg0);
            return result;
        }
    }
    async addSoftwareInquiry(arg0: SoftwareInquiry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSoftwareInquiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSoftwareInquiry(arg0);
            return result;
        }
    }
    async addTask(arg0: Task): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.addTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTask(arg0);
            return result;
        }
    }
    async addTelecaller(arg0: Telecaller): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTelecaller(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTelecaller(arg0);
            return result;
        }
    }
    async deleteLead(arg0: LeadId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLead(arg0);
            return result;
        }
    }
    async deleteProject(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async deleteProjectInquiry(arg0: InquiryId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProjectInquiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProjectInquiry(arg0);
            return result;
        }
    }
    async deleteTask(arg0: TaskId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async deleteTelecaller(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTelecaller(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTelecaller(arg0);
            return result;
        }
    }
    async getAllLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeads();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeads();
            return result;
        }
    }
    async getAllProjectInquiries(): Promise<Array<ProjectInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjectInquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjectInquiries();
            return result;
        }
    }
    async getAllProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return result;
        }
    }
    async getAllSoftwareInquiries(): Promise<Array<SoftwareInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSoftwareInquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSoftwareInquiries();
            return result;
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return result;
        }
    }
    async getAllTelecallers(): Promise<Array<Telecaller>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTelecallers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTelecallers();
            return result;
        }
    }
    async getBrochureLink(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBrochureLink(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBrochureLink(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallHistory(arg0: string | null): Promise<Array<CallHistory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallHistory(to_candid_opt_n2(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallHistory(to_candid_opt_n2(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getLeadById(arg0: LeadId): Promise<Lead | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadById(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadById(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadSchema(): Promise<Array<ColumnDef>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadSchema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadSchema();
            return result;
        }
    }
    async getLeadsBySalesPerson(arg0: string): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsBySalesPerson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsBySalesPerson(arg0);
            return result;
        }
    }
    async getLeadsByTelecaller(arg0: string): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsByTelecaller(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsByTelecaller(arg0);
            return result;
        }
    }
    async getSalesCallHistory(arg0: string | null): Promise<Array<SalesCallHistory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesCallHistory(to_candid_opt_n2(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesCallHistory(to_candid_opt_n2(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getTaskById(arg0: TaskId): Promise<Task | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaskById(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaskById(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksByAssignee(arg0: string): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByAssignee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByAssignee(arg0);
            return result;
        }
    }
    async getUniqueProjectNames(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUniqueProjectNames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUniqueProjectNames();
            return result;
        }
    }
    async getUniqueSalesPersons(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUniqueSalesPersons();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUniqueSalesPersons();
            return result;
        }
    }
    async getUniqueTelecallers(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUniqueTelecallers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUniqueTelecallers();
            return result;
        }
    }
    async removeColumnDef(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeColumnDef(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeColumnDef(arg0);
            return result;
        }
    }
    async updateLead(arg0: Lead): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLead(arg0);
            return result;
        }
    }
    async updateProject(arg0: string, arg1: Project): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, arg1);
            return result;
        }
    }
    async updateTask(arg0: Task): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0);
            return result;
        }
    }
    async updateTaskStatus(arg0: TaskId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskStatus(arg0, arg1);
            return result;
        }
    }
    async updateTelecaller(arg0: string, arg1: Telecaller): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTelecaller(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTelecaller(arg0, arg1);
            return result;
        }
    }
    async upsertColumnDef(arg0: ColumnDef): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertColumnDef(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertColumnDef(arg0);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Lead]): Lead | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Task]): Task | null {
    return value.length === 0 ? null : value[0];
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
